artifacts_root: artifacts

data_ingestion:
  local_data_file: artifacts/data_ingestion
  root_dir: artifacts/data_ingestion
  ticker: AAPL

data_validation:
  STATUS_FILE: artifacts/data_validation/status.txt
  local_data_file: artifacts/data_ingestion/data.csv
  root_dir: artifacts/data_validation